// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm_c2QL20PU7eQMeTaliqxuzO3ROFukb8',
    appId: '1:361156205738:web:9e162774b0b5fe848a04d3',
    messagingSenderId: '361156205738',
    projectId: 'fresh-fruit-9c78b',
    authDomain: 'fresh-fruit-9c78b.firebaseapp.com',
    storageBucket: 'fresh-fruit-9c78b.firebasestorage.app',
    measurementId: 'G-9NTXMGPZL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZaEnoufbg4Y1cfg2Fax9Xnu3eVA-Z8Ro',
    appId: '1:361156205738:android:2780c25c0614e8608a04d3',
    messagingSenderId: '361156205738',
    projectId: 'fresh-fruit-9c78b',
    storageBucket: 'fresh-fruit-9c78b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9VLn4J32QTTcGeM1dBKyQO8fVOQuDFWk',
    appId: '1:361156205738:ios:7689a21aff113abc8a04d3',
    messagingSenderId: '361156205738',
    projectId: 'fresh-fruit-9c78b',
    storageBucket: 'fresh-fruit-9c78b.firebasestorage.app',
    iosBundleId: 'com.example.freshFruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9VLn4J32QTTcGeM1dBKyQO8fVOQuDFWk',
    appId: '1:361156205738:ios:7689a21aff113abc8a04d3',
    messagingSenderId: '361156205738',
    projectId: 'fresh-fruit-9c78b',
    storageBucket: 'fresh-fruit-9c78b.firebasestorage.app',
    iosBundleId: 'com.example.freshFruit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm_c2QL20PU7eQMeTaliqxuzO3ROFukb8',
    appId: '1:361156205738:web:d7399fb8b2ac2b398a04d3',
    messagingSenderId: '361156205738',
    projectId: 'fresh-fruit-9c78b',
    authDomain: 'fresh-fruit-9c78b.firebaseapp.com',
    storageBucket: 'fresh-fruit-9c78b.firebasestorage.app',
    measurementId: 'G-5X7M8CWZG6',
  );
}
